// faker
import { 
  faker,
} from '@faker-js/faker';
// type
import { 
  TMathTextbookModel,
} from '@/apis/models/mathModel.type';

export const mockMathTextbookData: TMathTextbookModel[] = [
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학1 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '1학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학2 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '1학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학3 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '1학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학1 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '2학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학2 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '2학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학3 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '2학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학1 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '3학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학2 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '3학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학3 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '3학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학1 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '1학년',
    term: '1학기',
  },

  // 10
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학1 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '1학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학2 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '1학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학3 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '1학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학1 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '2학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학2 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '2학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학3 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '2학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학1 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '3학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학2 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '3학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학3 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '3학년',
    term: '공통',
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    name: '수학1 (박)',
    author: '박교식',
    classType: '중학교',
    grade: '1학년',
    term: '1학기',
  },
];
