// faker
import { 
  faker,
} from '@faker-js/faker';
// type
import { 
  TMathTextbookModel,
} from '@/apis/models/mathModel.type';

export const mockMathTextbookData: TMathTextbookModel[] = [
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학1 (박)',
    author: '박교식',
    classType: '고등',
    grade: 1,
    term: 0,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학2 (박)',
    author: '박교식',
    classType: '중등',
    grade: 2,
    term: 0,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학3 (박)',
    author: '박교식',
    classType: '초등',
    grade: 6,
    term: 0,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학1 (박)',
    author: '박교식',
    classType: '고등',
    grade: 2,
    term: 1,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학2 (박)',
    author: '박교식',
    classType: '중등',
    grade: 2,
    term: 1,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학3 (박)',
    author: '박교식',
    classType: '초등',
    grade: 2,
    term: 1,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학1 (박)',
    author: '박교식',
    classType: '고등',
    grade: 3,
    term: 2,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학2 (박)',
    author: '박교식',
    classType: '중등',
    grade: 3,
    term: 2,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학3 (박)',
    author: '박교식',
    classType: '초등',
    grade: 3,
    term: 2,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학1 (박)',
    author: '박교식',
    classType: '초등',
    grade: 1,
    term: 0,
  },

  // 10
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학1 (박)',
    author: '박교식',
    classType: '초등',
    grade: 2,
    term: 1,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학2 (박)',
    author: '박교식',
    classType: '초등',
    grade: 3,
    term: 1,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학3 (박)',
    author: '박교식',
    classType: '초등',
    grade: 4,
    term: 1,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학1 (박)',
    author: '박교식',
    classType: '초등',
    grade: 5,
    term: 2,
  },
  {
    id: faker.string.uuid(),
    subject: '수학',
    curriculum: '2015',
    title: '수학2 (박)',
    author: '박교식',
    classType: '초등',
    grade: 6,
    term: 2,
  },
];
