// type
import { 
  TMathQuestionModel,
} from '../models/mathModel.type';

const mockMathQuestion: TMathQuestionModel = {
  "id": 9,
  "internal_id": "741501",
  "source": {
    "id": 1,
    "name": "고등 코드엠 수학(상)",
    "curriculum": "2015",
    "classtype": "고등",
    "grade": 1,
    "term": 0,
    "serviceyear": "2018",
    "publisher": "동아출판㈜",
    "expiration_date": "9999-12-31",
    "source_type": "교사용부록",
    "isview": true
  },
  "instruction": null,
  "achievement": [
    {
      "id": 1,
      "title": "다항식의 사칙연산을 할 수 있다.",
      "no": "01",
      "code": "[10수학01-01]"
    }
  ],
  "curriculum": "2015",
  "subject": "수학",
  "keyword": "|다항식|나눗셈|곱셈|뺄셈|다항식의 나눗셈|다항식의 나눗셈에서 몫과 나머지 알아보기|",
  "behavior_domain": "이해",
  "inquiry": "다음은 다항식 $3 x^2-2 x^2-4 x-7$ 을 $x-2$ 로 나누는 과정을 나타낸 것이다. 이때 상수 $a, b, c, d$ 에 대하여 $a+b+c+d$ 의 값을 구하시오.\n<img src=\"https://donga-cms-files.s3.ap-northeast-2.amazonaws.com/images/741501_Q.png\" alt=\"이미지 설명\">",
  "choice1": "",
  "choice2": "",
  "choice3": "",
  "choice4": "",
  "choice5": "",
  "choice_answer": "",
  "short_answer_count": 1,
  "short_answer1": "$16$",
  "short_answer2": "",
  "short_answer3": "",
  "short_answer4": "",
  "short_answer5": "",
  "short_answer6": "",
  "short_answer7": "",
  "short_answer8": "",
  "short_answer9": "",
  "short_answer10": "",
  "short_answer11": "",
  "short_answer12": "",
  "short_answer13": "",
  "short_answer14": "",
  "short_answer15": "",
  "short_answer16": "",
  "short_answer17": "",
  "short_answer18": "",
  "short_answer19": "",
  "short_answer20": "",
  "solution": "<img src=\"https://donga-cms-files.s3.ap-northeast-2.amazonaws.com/images/741501_A.png\" alt=\"이미지 설명\">\n따라서 $a=4, b=4, c=7, d=1$이므로<br> $a+b+c+d=4+4+7+1=16$",
  "evaluation_criteria1": "",
  "evaluation_criteria1_percent": "nan",
  "evaluation_criteria2": "",
  "evaluation_criteria2_percent": "nan",
  "evaluation_criteria3": "",
  "evaluation_criteria3_percent": "nan",
  "evaluation_criteria4": "",
  "evaluation_criteria4_percent": "nan",
  "evaluation_criteria5": "",
  "evaluation_criteria5_percent": "",
  "difficulty": 3,
  "question_type": "주관식-단답형",
  "choice_type": null,
  "choice_count": null,
  "is_set": false,
  "representation_question_id": null,
  "individual_questioning": false,
  "source_page_no": 27,
  "source_question_no": "",
  "is_reviewed": false,
  "kc1_title": "다항식의 나눗셈에서 몫과 나머지 알아보기",
  "kc2_title": "다항식의 나눗셈"
};

export default mockMathQuestion;
