// type
import { 
  TRetrieveMathSeriesSourcesApiResponse,
} from '@/apis/math/mathApi.type';

const mockMathSeriesSources: TRetrieveMathSeriesSourcesApiResponse = {
  "current_page": 1,
  "last_page": 1,
  "page_size": 100,
  "count": 14,
  "previous": null,
  "next": null,
  "results": [
    {
      "id": 341,
      "title": "수매씽",
      "source_set": [
        {
          "id": 1100,
          "name": "수매씽 고등 수학(상)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1101,
          "name": "수매씽 미적분",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1102,
          "name": "수매씽 수학Ⅰ",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1103,
          "name": "수매씽 고등 수학(하)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1104,
          "name": "수매씽 확률과 통계",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1111,
          "name": "수매씽 중학 수학 1-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1112,
          "name": "수매씽 중학 수학 1-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1113,
          "name": "수매씽 중학 수학 1-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1115,
          "name": "수매씽 중학 수학 1-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1116,
          "name": "수매씽 중학 수학 1-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1117,
          "name": "수매씽 중학 수학 1-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1119,
          "name": "수매씽 중학 수학 2-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1120,
          "name": "수매씽 중학 수학 2-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1121,
          "name": "수매씽 중학 수학 2-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1123,
          "name": "수매씽 중학 수학 2-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1124,
          "name": "수매씽 중학 수학 2-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1125,
          "name": "수매씽 중학 수학 2-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1127,
          "name": "수매씽 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1128,
          "name": "수매씽 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1129,
          "name": "수매씽 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1131,
          "name": "수매씽 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1132,
          "name": "수매씽 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1133,
          "name": "수매씽 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1181,
          "name": "수매씽 수학Ⅱ",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1184,
          "name": "수매씽 개념 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2024",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1185,
          "name": "수매씽 개념 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2024",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용 지도자료",
          "isview": true
        },
        {
          "id": 1186,
          "name": "수매씽 개념 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2024",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1188,
          "name": "수매씽 개념 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2024",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1189,
          "name": "수매씽 개념 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2024",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용 지도자료",
          "isview": true
        },
        {
          "id": 1190,
          "name": "수매씽 개념 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2024",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        }
      ]
    },
    {
      "id": 342,
      "title": "절대등급",
      "source_set": [
        {
          "id": 1105,
          "name": "절대등급 미적분",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1106,
          "name": "절대등급 고등 수학(상)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1107,
          "name": "절대등급 수학Ⅰ",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1108,
          "name": "절대등급 수학Ⅱ",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1109,
          "name": "절대등급 고등 수학(하)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1110,
          "name": "절대등급 확률과 통계",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1114,
          "name": "절대등급 중학 수학 1-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1118,
          "name": "절대등급 중학 수학 1-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1122,
          "name": "절대등급 중학 수학 2-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1126,
          "name": "절대등급 중학 수학 2-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1130,
          "name": "절대등급 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1134,
          "name": "절대등급 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        }
      ]
    },
    {
      "id": 343,
      "title": "동아전과 자습서&평가문제집",
      "source_set": [
        {
          "id": 1135,
          "name": "동아전과 자습서&평가문제집 초등 수학(박) 3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "자습서",
          "isview": true
        },
        {
          "id": 1136,
          "name": "동아전과 자습서&평가문제집 초등 수학(박) 3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가문제집",
          "isview": true
        },
        {
          "id": 1137,
          "name": "동아전과 자습서&평가문제집 초등 수학(안) 3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "자습서",
          "isview": true
        },
        {
          "id": 1138,
          "name": "동아전과 자습서&평가문제집 초등 수학(안) 3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가문제집",
          "isview": true
        },
        {
          "id": 1142,
          "name": "동아전과 자습서&평가문제집 초등 수학(박) 3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "자습서",
          "isview": true
        },
        {
          "id": 1143,
          "name": "동아전과 자습서&평가문제집 초등 수학(박) 3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가문제집",
          "isview": true
        },
        {
          "id": 1144,
          "name": "동아전과 자습서&평가문제집 초등 수학(안) 3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "자습서",
          "isview": true
        },
        {
          "id": 1145,
          "name": "동아전과 자습서&평가문제집 초등 수학(안) 3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가문제집",
          "isview": true
        },
        {
          "id": 1149,
          "name": "동아전과 자습서&평가문제집 초등 수학(박) 4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "자습서",
          "isview": true
        },
        {
          "id": 1150,
          "name": "동아전과 자습서&평가문제집 초등 수학(박) 4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가문제집",
          "isview": true
        },
        {
          "id": 1151,
          "name": "동아전과 자습서&평가문제집 초등 수학(안) 4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "자습서",
          "isview": true
        },
        {
          "id": 1152,
          "name": "동아전과 자습서&평가문제집 초등 수학(안) 4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가문제집",
          "isview": true
        },
        {
          "id": 1156,
          "name": "동아전과 자습서&평가문제집 초등 수학(박) 4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "자습서",
          "isview": true
        },
        {
          "id": 1157,
          "name": "동아전과 자습서&평가문제집 초등 수학(박) 4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가문제집",
          "isview": true
        },
        {
          "id": 1158,
          "name": "동아전과 자습서&평가문제집 초등 수학(안) 4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "자습서",
          "isview": true
        },
        {
          "id": 1159,
          "name": "동아전과 자습서&평가문제집 초등 수학(안) 4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가문제집",
          "isview": true
        },
        {
          "id": 1162,
          "name": "동아전과 교과서 평가문제집 초등 수학(공통) 5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        },
        {
          "id": 1166,
          "name": "동아전과 교과서 평가문제집 초등 수학(공통) 5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        },
        {
          "id": 1170,
          "name": "동아전과 교과서 평가문제집 초등 수학(공통) 6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        },
        {
          "id": 1174,
          "name": "동아전과 교과서 평가문제집 초등 수학(공통) 6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        }
      ]
    },
    {
      "id": 344,
      "title": "큐브수학",
      "source_set": [
        {
          "id": 1139,
          "name": "큐브수학 개념응용 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1140,
          "name": "큐브수학 개념응용 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "응용강화북",
          "isview": true
        },
        {
          "id": 1141,
          "name": "큐브수학 개념응용 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1146,
          "name": "큐브수학 개념응용 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1147,
          "name": "큐브수학 개념응용 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "응용강화북",
          "isview": true
        },
        {
          "id": 1148,
          "name": "큐브수학 개념응용 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1153,
          "name": "큐브수학 개념응용 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1154,
          "name": "큐브수학 개념응용 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "응용강화북",
          "isview": true
        },
        {
          "id": 1155,
          "name": "큐브수학 개념응용 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1160,
          "name": "큐브수학 개념응용 초4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "응용강화북",
          "isview": true
        },
        {
          "id": 1161,
          "name": "큐브수학 개념응용 초4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1163,
          "name": "큐브수학 개념응용 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1164,
          "name": "큐브수학 개념응용 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "응용강화북",
          "isview": true
        },
        {
          "id": 1165,
          "name": "큐브수학 개념응용 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1167,
          "name": "큐브수학 개념응용 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1168,
          "name": "큐브수학 개념응용 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "응용강화북",
          "isview": true
        },
        {
          "id": 1169,
          "name": "큐브수학 개념응용 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1171,
          "name": "큐브수학 개념응용 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1172,
          "name": "큐브수학 개념응용 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "응용강화북",
          "isview": true
        },
        {
          "id": 1173,
          "name": "큐브수학 개념응용 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1175,
          "name": "큐브수학 개념응용 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1176,
          "name": "큐브수학 개념응용 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "응용강화북",
          "isview": true
        },
        {
          "id": 1177,
          "name": "큐브수학 개념응용 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1199,
          "name": "큐브수학 심화 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1200,
          "name": "큐브수학 심화 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1201,
          "name": "큐브수학 심화 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1202,
          "name": "큐브수학 심화 초4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1203,
          "name": "큐브수학 심화 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1204,
          "name": "큐브수학 심화 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1205,
          "name": "큐브수학 심화 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1206,
          "name": "큐브수학 심화 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1207,
          "name": "큐브수학 심화 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "경시대비북",
          "isview": true
        },
        {
          "id": 1208,
          "name": "큐브수학 심화 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "경시대비북",
          "isview": true
        },
        {
          "id": 1209,
          "name": "큐브수학 심화 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "경시대비북",
          "isview": true
        },
        {
          "id": 1210,
          "name": "큐브수학 심화 초4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "경시대비북",
          "isview": true
        },
        {
          "id": 1211,
          "name": "큐브수학 심화 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "경시대비북",
          "isview": true
        },
        {
          "id": 1212,
          "name": "큐브수학 심화 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "경시대비북",
          "isview": true
        },
        {
          "id": 1213,
          "name": "큐브수학 심화 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "경시대비북",
          "isview": true
        },
        {
          "id": 1214,
          "name": "큐브수학 심화 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "경시대비북",
          "isview": true
        },
        {
          "id": 1217,
          "name": "큐브수학 심화 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1218,
          "name": "큐브수학 심화 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1219,
          "name": "큐브수학 심화 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1220,
          "name": "큐브수학 심화 초4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1221,
          "name": "큐브수학 심화 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1222,
          "name": "큐브수학 심화 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1223,
          "name": "큐브수학 심화 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1224,
          "name": "큐브수학 심화 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2022",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1252,
          "name": "큐브수학 개념 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1253,
          "name": "큐브수학 개념 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1254,
          "name": "큐브수학 개념 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1255,
          "name": "큐브수학 개념 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1256,
          "name": "큐브수학 개념 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1257,
          "name": "큐브수학 개념 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1258,
          "name": "큐브수학 실력 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1259,
          "name": "큐브수학 실력 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1260,
          "name": "큐브수학 실력 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1261,
          "name": "큐브수학 실력 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1262,
          "name": "큐브수학 실력 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1263,
          "name": "큐브수학 실력 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1271,
          "name": "큐브수학 개념 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1273,
          "name": "큐브수학 개념 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1274,
          "name": "큐브수학 개념 초4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1275,
          "name": "큐브수학 개념 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1276,
          "name": "큐브수학 실력 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1277,
          "name": "큐브수학 개념 초4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1278,
          "name": "큐브수학 개념 초4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1279,
          "name": "큐브수학 실력 초3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1291,
          "name": "큐브수학 개념 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1292,
          "name": "큐브수학 개념 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1293,
          "name": "큐브수학 개념 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1298,
          "name": "큐브수학 개념 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1301,
          "name": "큐브수학 실력 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1302,
          "name": "큐브수학 실력 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1303,
          "name": "큐브수학 실력 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1304,
          "name": "큐브수학 실력 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1310,
          "name": "큐브수학 개념 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1311,
          "name": "큐브수학 개념 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1312,
          "name": "큐브수학 개념 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1313,
          "name": "큐브수학 개념 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "진도북",
          "isview": true
        },
        {
          "id": 1314,
          "name": "큐브수학 개념 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1315,
          "name": "큐브수학 개념 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1316,
          "name": "큐브수학 실력 초5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "매칭북",
          "isview": true
        },
        {
          "id": 1319,
          "name": "큐브수학 실력 초6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        }
      ]
    },
    {
      "id": 345,
      "title": "날선개념",
      "source_set": [
        {
          "id": 1178,
          "name": "날선개념 고등 수학(상)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1179,
          "name": "날선개념 수학Ⅰ",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1180,
          "name": "날선개념 고등 수학(하)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1192,
          "name": "날선개념 수학Ⅱ",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1193,
          "name": "날선개념 확률과 통계",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1194,
          "name": "날선개념 미적분",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        }
      ]
    },
    {
      "id": 346,
      "title": "특급기출",
      "source_set": [
        {
          "id": 1182,
          "name": "특급기출 중학 수학 2-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "중간고사",
          "isview": true
        },
        {
          "id": 1183,
          "name": "특급기출 중학 수학 2-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "중간고사",
          "isview": true
        },
        {
          "id": 1187,
          "name": "특급기출 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "중간고사",
          "isview": true
        },
        {
          "id": 1191,
          "name": "특급기출 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기말고사",
          "isview": true
        },
        {
          "id": 1195,
          "name": "특급기출 중학 수학 2-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기말고사",
          "isview": true
        },
        {
          "id": 1196,
          "name": "특급기출 중학 수학 2-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기말고사",
          "isview": true
        },
        {
          "id": 1197,
          "name": "특급기출 중학 수학 3-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기말고사",
          "isview": true
        },
        {
          "id": 1198,
          "name": "특급기출 중학 수학 3-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "중간고사",
          "isview": true
        }
      ]
    },
    {
      "id": 347,
      "title": "백점 시리즈",
      "source_set": [
        {
          "id": 1215,
          "name": "백점 수학 5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1216,
          "name": "백점 수학 3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1225,
          "name": "백점 수학 3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1226,
          "name": "백점 수학 4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1227,
          "name": "백점 수학 4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1228,
          "name": "백점 수학 5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1229,
          "name": "백점 수학 6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1230,
          "name": "백점 수학 6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1231,
          "name": "백점 수학 3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가북",
          "isview": true
        },
        {
          "id": 1232,
          "name": "백점 수학 3-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가북",
          "isview": true
        },
        {
          "id": 1233,
          "name": "백점 수학 4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가북",
          "isview": true
        },
        {
          "id": 1234,
          "name": "백점 수학 4-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가북",
          "isview": true
        },
        {
          "id": 1235,
          "name": "백점 수학 5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가북",
          "isview": true
        },
        {
          "id": 1236,
          "name": "백점 수학 5-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가북",
          "isview": true
        },
        {
          "id": 1237,
          "name": "백점 수학 6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가북",
          "isview": true
        },
        {
          "id": 1238,
          "name": "백점 수학 6-2",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 2,
          "serviceyear": "2023",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "평가북",
          "isview": true
        }
      ]
    },
    {
      "id": 348,
      "title": "코드엠",
      "source_set": [
        {
          "id": 1239,
          "name": "코드엠 고등 수학(상)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1240,
          "name": "코드엠 고등 수학(하)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1241,
          "name": "코드엠 고등 수학(상)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1242,
          "name": "코드엠 고등 수학(하)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1247,
          "name": "코드엠 수학I",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1248,
          "name": "코드엠 수학I",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1285,
          "name": "코드엠 절대등급 고등 수학(상)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1287,
          "name": "코드엠 절대등급 고등 수학(하)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        }
      ]
    },
    {
      "id": 349,
      "title": "빨리 강해지는 수학",
      "source_set": [
        {
          "id": 1243,
          "name": "중1-1 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1244,
          "name": "중1-1 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "실전북",
          "isview": true
        },
        {
          "id": 1245,
          "name": "중1-1 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1280,
          "name": "중1-2 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1281,
          "name": "중1-2 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "실전북",
          "isview": true
        },
        {
          "id": 1282,
          "name": "중1-2 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1294,
          "name": "중2-1 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1295,
          "name": "중2-1 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "실전북",
          "isview": true
        },
        {
          "id": 1296,
          "name": "중2-1 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1317,
          "name": "중2-2 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "유형북",
          "isview": true
        },
        {
          "id": 1318,
          "name": "중2-2 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1321,
          "name": "중2-2 빨리 강해지는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "실전북",
          "isview": true
        }
      ]
    },
    {
      "id": 350,
      "title": "빨리 이해하는 수학",
      "source_set": [
        {
          "id": 1246,
          "name": "중1-1 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1249,
          "name": "중1-1 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1250,
          "name": "중1-1 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1251,
          "name": "중1-1 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "학생용부록",
          "isview": true
        },
        {
          "id": 1283,
          "name": "중1-2 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1284,
          "name": "중1-2 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1297,
          "name": "중2-1 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1299,
          "name": "중2-1 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1300,
          "name": "중2-1 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1320,
          "name": "중2-2 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "개념북",
          "isview": true
        },
        {
          "id": 1322,
          "name": "중2-2 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "워크북",
          "isview": true
        },
        {
          "id": 1323,
          "name": "중2-2 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "교사용부록",
          "isview": true
        },
        {
          "id": 1324,
          "name": "중2-2 빨리 이해하는 수학",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "학생용부록",
          "isview": true
        }
      ]
    },
    {
      "id": 351,
      "title": "평가스크랩",
      "source_set": [
        {
          "id": 1264,
          "name": "평가자료집 수학 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "서술형평가",
          "isview": true
        },
        {
          "id": 1265,
          "name": "평가자료집 수학 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "서술형평가",
          "isview": true
        },
        {
          "id": 1266,
          "name": "평가자료집 수학 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "단원평가",
          "isview": true
        },
        {
          "id": 1267,
          "name": "평가자료집 수학 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "단원평가",
          "isview": true
        },
        {
          "id": 1268,
          "name": "평가자료집 수학 초3-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 3,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기말고사",
          "isview": true
        },
        {
          "id": 1269,
          "name": "평가자료집 수학 초4-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 4,
          "term": 1,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기말고사",
          "isview": true
        },
        {
          "id": 1306,
          "name": "평가자료집 수학 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "단원평가",
          "isview": true
        },
        {
          "id": 1307,
          "name": "평가자료집 수학 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "단원평가",
          "isview": true
        },
        {
          "id": 1308,
          "name": "평가자료집 수학 초5-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 5,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "서술형평가",
          "isview": true
        },
        {
          "id": 1309,
          "name": "평가자료집 수학 초6-1",
          "curriculum": "2015",
          "classtype": "초등",
          "grade": 6,
          "term": 1,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "서술형평가",
          "isview": true
        }
      ]
    },
    {
      "id": 352,
      "title": "교사용CD",
      "source_set": [
        {
          "id": 1270,
          "name": "중1 수학 교사용 CD",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        },
        {
          "id": 1272,
          "name": "고등 수학 교사용 CD",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        },
        {
          "id": 1305,
          "name": "중2 수학 교사용 CD",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 2,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        },
        {
          "id": 1325,
          "name": "중3 수학 교사용 CD",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 3,
          "term": 0,
          "serviceyear": "2020",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        }
      ]
    },
    {
      "id": 353,
      "title": "두클래스",
      "source_set": [
        {
          "id": 1286,
          "name": "시험대비자료집 수학 중1-1",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        },
        {
          "id": 1288,
          "name": "시험대비자료집 수학 중1-2",
          "curriculum": "2015",
          "classtype": "중등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2018",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "기타",
          "isview": true
        }
      ]
    },
    {
      "id": 354,
      "title": "날선유형",
      "source_set": [
        {
          "id": 1289,
          "name": "날선유형 고등 수학(상)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        },
        {
          "id": 1290,
          "name": "날선유형 고등 수학(하)",
          "curriculum": "2015",
          "classtype": "고등",
          "grade": 1,
          "term": 0,
          "serviceyear": "2019",
          "publisher": "동아출판㈜",
          "expiration_date": "9999-12-31",
          "source_type": "본책",
          "isview": true
        }
      ]
    }
  ]
};

export default mockMathSeriesSources;
